# Generated by Django 4.2.4 on 2023-08-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_body_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
