# Generated by Django 4.2.4 on 2023-09-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_coffeeman_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeman',
            name='time_stamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
