# Generated by Django 4.2.4 on 2023-09-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_coffeeman_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeman',
            name='can_drink',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='view_count',
        ),
        migrations.AddField(
            model_name='coffeeman',
            name='coffee_pool',
            field=models.IntegerField(default=100),
        ),
    ]
