# Generated by Django 4.2.4 on 2023-09-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeman',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
