# Generated by Django 4.2.4 on 2023-09-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_coffeeman_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
